services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME:-db_mission_planner}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pass}
    ports:
      - "${DB_PORT:-5432:5432}"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/database/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-user} -d ${DB_NAME:-db}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    restart: "no"

  mqtt:
    image: eclipse-mosquitto:2
    restart: "no"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    ports:
      - "9000:9000"
      - "9002:9001"
    volumes:
      - minio_data:/data

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data
    environment:
      - TZ=Europe/London

volumes:
  db_data:
  mosquitto_data:
  mosquitto_log:
  minio_data:
  nodered_data:
