/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObservationsIndexRouteImport } from './routes/observations/index'
import { Route as ObservationsExternalIdRouteImport } from './routes/observations/$externalId'
import { Route as RulesIndexRouteImport } from './routes/rules/index'
import { Route as RulesExternalIdRouteImport } from './routes/rules/$externalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservationsIndexRoute = ObservationsIndexRouteImport.update({
  id: '/observations/',
  path: '/observations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservationsExternalIdRoute = ObservationsExternalIdRouteImport.update({
  id: '/observations/$externalId',
  path: '/observations/$externalId',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesIndexRoute = RulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesExternalIdRoute = RulesExternalIdRouteImport.update({
  id: '/rules/$externalId',
  path: '/rules/$externalId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/observations/$externalId': typeof ObservationsExternalIdRoute
  '/rules/$externalId': typeof RulesExternalIdRoute
  '/observations/': typeof ObservationsIndexRoute
  '/rules/': typeof RulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/observations/$externalId': typeof ObservationsExternalIdRoute
  '/rules/$externalId': typeof RulesExternalIdRoute
  '/observations': typeof ObservationsIndexRoute
  '/rules': typeof RulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/observations/$externalId': typeof ObservationsExternalIdRoute
  '/rules/$externalId': typeof RulesExternalIdRoute
  '/observations/': typeof ObservationsIndexRoute
  '/rules/': typeof RulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/observations/$externalId'
    | '/rules/$externalId'
    | '/observations/'
    | '/rules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/observations/$externalId'
    | '/rules/$externalId'
    | '/observations'
    | '/rules'
  id:
    | '__root__'
    | '/'
    | '/observations/$externalId'
    | '/rules/$externalId'
    | '/observations/'
    | '/rules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ObservationsExternalIdRoute: typeof ObservationsExternalIdRoute
  RulesExternalIdRoute: typeof RulesExternalIdRoute
  ObservationsIndexRoute: typeof ObservationsIndexRoute
  RulesIndexRoute: typeof RulesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observations/': {
      id: '/observations/'
      path: '/observations'
      fullPath: '/observations/'
      preLoaderRoute: typeof ObservationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observations/$externalId': {
      id: '/observations/$externalId'
      path: '/observations/$externalId'
      fullPath: '/observations/$externalId'
      preLoaderRoute: typeof ObservationsExternalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/': {
      id: '/rules/'
      path: '/rules'
      fullPath: '/rules/'
      preLoaderRoute: typeof RulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/$externalId': {
      id: '/rules/$externalId'
      path: '/rules/$externalId'
      fullPath: '/rules/$externalId'
      preLoaderRoute: typeof RulesExternalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ObservationsExternalIdRoute: ObservationsExternalIdRoute,
  RulesExternalIdRoute: RulesExternalIdRoute,
  ObservationsIndexRoute: ObservationsIndexRoute,
  RulesIndexRoute: RulesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
